"""seniors

Revision ID: 0001
Revises: 
Create Date: 2026-07-14 10:22:39.044697
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seniors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=32), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('pesel_enc', sa.String(length=256), nullable=True),
    sa.Column('pesel_bidx', sa.String(length=64), nullable=True),
    sa.Column('phone_enc', sa.String(length=256), nullable=True),
    sa.Column('phone_bidx', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('district', sa.String(length=80), nullable=True),
    sa.Column('package', sa.Enum('basic', 'family', 'premium', name='package'), nullable=False),
    sa.Column('semaphore', sa.Enum('green', 'yellow', 'red', 'purple', name='semaphorelevel'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('seniors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seniors_district'), ['district'], unique=False)
        batch_op.create_index(batch_op.f('ix_seniors_external_id'), ['external_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_seniors_pesel_bidx'), ['pesel_bidx'], unique=False)
        batch_op.create_index(batch_op.f('ix_seniors_phone_bidx'), ['phone_bidx'], unique=False)
        batch_op.create_index(batch_op.f('ix_seniors_semaphore'), ['semaphore'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seniors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seniors_semaphore'))
        batch_op.drop_index(batch_op.f('ix_seniors_phone_bidx'))
        batch_op.drop_index(batch_op.f('ix_seniors_pesel_bidx'))
        batch_op.drop_index(batch_op.f('ix_seniors_external_id'))
        batch_op.drop_index(batch_op.f('ix_seniors_district'))

    op.drop_table('seniors')
    # ### end Alembic commands ###
