"""scheduler campaigns and call_attempts

Revision ID: 0002
Revises: 0001
Create Date: 2026-07-14 10:26:08.436325
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.Enum('morning', 'evening', 'medication', 'custom', name='campaignkind'), nullable=False),
    sa.Column('scheduled_time', sa.Time(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('retry_interval_s', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('call_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('senior_id', sa.Integer(), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'dialing', 'answered', 'no_answer', 'failed', 'exhausted', 'completed', name='callstatus'), nullable=False),
    sa.Column('channel_id', sa.String(length=64), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['senior_id'], ['seniors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('call_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_call_attempts_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_attempts_senior_id'), ['senior_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_attempts_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_attempts_status'))
        batch_op.drop_index(batch_op.f('ix_call_attempts_senior_id'))
        batch_op.drop_index(batch_op.f('ix_call_attempts_campaign_id'))

    op.drop_table('call_attempts')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
