"""semaphore events

Revision ID: 0003
Revises: 0002
Create Date: 2026-07-14 11:11:11.735999
"""
from alembic import op
import sqlalchemy as sa


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('semaphore_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('senior_id', sa.Integer(), nullable=False),
    sa.Column('previous_level', sa.Enum('green', 'yellow', 'red', 'purple', name='semaphorelevel'), nullable=False),
    sa.Column('new_level', sa.Enum('green', 'yellow', 'red', 'purple', name='semaphorelevel'), nullable=False),
    sa.Column('trigger', sa.Enum('routine_ok', 'mood_low', 'missed_medication', 'poor_sleep', 'social_isolation', 'minor_complaint', 'no_answer_exhausted', 'vitals_out_of_range', 'persistent_pain', 'confusion', 'fall_reported', 'chest_pain', 'breathing_difficulty', 'stroke_symptoms', 'suicide_ideation', 'unconscious', 'severe_bleeding', name='trigger'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('signals', sa.Text(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['senior_id'], ['seniors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('semaphore_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_semaphore_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_semaphore_events_new_level'), ['new_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_semaphore_events_senior_id'), ['senior_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_semaphore_events_trigger'), ['trigger'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('semaphore_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_semaphore_events_trigger'))
        batch_op.drop_index(batch_op.f('ix_semaphore_events_senior_id'))
        batch_op.drop_index(batch_op.f('ix_semaphore_events_new_level'))
        batch_op.drop_index(batch_op.f('ix_semaphore_events_created_at'))

    op.drop_table('semaphore_events')
    # ### end Alembic commands ###
