"""medication tracker

Revision ID: 0004
Revises: 0003
Create Date: 2026-07-14 11:15:24.680088
"""
from alembic import op
import sqlalchemy as sa


revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('senior_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('dosage', sa.String(length=80), nullable=True),
    sa.Column('form', sa.Enum('tablet', 'capsule', 'liquid', 'injection', 'drops', 'inhaler', 'patch', 'other', name='medform'), nullable=False),
    sa.Column('instructions', sa.String(length=500), nullable=True),
    sa.Column('prescriber', sa.String(length=120), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['senior_id'], ['seniors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medications_senior_id'), ['senior_id'], unique=False)

    op.create_table('dose_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('medication_id', sa.Integer(), nullable=False),
    sa.Column('senior_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'taken', 'missed', 'skipped', 'late', name='dosestatus'), nullable=False),
    sa.Column('taken_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ),
    sa.ForeignKeyConstraint(['senior_id'], ['seniors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dose_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dose_logs_medication_id'), ['medication_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dose_logs_scheduled_at'), ['scheduled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_dose_logs_senior_id'), ['senior_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dose_logs_status'), ['status'], unique=False)

    op.create_table('medication_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('medication_id', sa.Integer(), nullable=False),
    sa.Column('at_time', sa.Time(), nullable=False),
    sa.Column('days_mask', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medication_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medication_schedules_medication_id'), ['medication_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medication_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medication_schedules_medication_id'))

    op.drop_table('medication_schedules')
    with op.batch_alter_table('dose_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dose_logs_status'))
        batch_op.drop_index(batch_op.f('ix_dose_logs_senior_id'))
        batch_op.drop_index(batch_op.f('ix_dose_logs_scheduled_at'))
        batch_op.drop_index(batch_op.f('ix_dose_logs_medication_id'))

    op.drop_table('dose_logs')
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medications_senior_id'))

    op.drop_table('medications')
    # ### end Alembic commands ###
