"""memory chunks

Revision ID: 0005
Revises: 0004
Create Date: 2026-07-14 11:18:05.077183
"""
from alembic import op
import sqlalchemy as sa


revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('senior_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('conversation', 'fact', 'preference', 'health_note', name='memorykind'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', sa.Text(), nullable=False),
    sa.Column('embed_model', sa.String(length=60), nullable=False),
    sa.Column('source_ref', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['senior_id'], ['seniors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memory_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memory_chunks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_chunks_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_chunks_senior_id'), ['senior_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memory_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memory_chunks_senior_id'))
        batch_op.drop_index(batch_op.f('ix_memory_chunks_kind'))
        batch_op.drop_index(batch_op.f('ix_memory_chunks_created_at'))

    op.drop_table('memory_chunks')
    # ### end Alembic commands ###
