"""family wearables marketplace rodo

Revision ID: 0006
Revises: 0005
Create Date: 2026-07-14 11:29:36.583405
"""
from alembic import op
import sqlalchemy as sa


revision = '0006'
down_revision = '0005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partners',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.Enum('medical_care', 'home_help', 'meals', 'transport', 'physiotherapy', 'shopping', 'companionship', 'repairs', 'hairdressing', 'legal_admin', name='servicecategory'), nullable=False),
    sa.Column('nip', sa.String(length=10), nullable=True),
    sa.Column('insurance_oc', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'verified', 'suspended', 'rejected', name='partnerstatus'), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('fraud_flags', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partners_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_partners_status'), ['status'], unique=False)

    op.create_table('data_processing_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('senior_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('export', 'soft_delete', 'erase', 'anonymize', 'retention_purge', 'access', name='processingaction'), nullable=False),
    sa.Column('category', sa.Enum('profile', 'recordings', 'transcripts', 'reports', 'memory', 'vitals', name='datacategory'), nullable=True),
    sa.Column('legal_basis', sa.String(length=120), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['senior_id'], ['seniors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_processing_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_processing_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_processing_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_processing_logs_senior_id'), ['senior_id'], unique=False)

    op.create_table('family_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('senior_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('primary', 'secondary', 'coordinator', 'observer', name='familyrole'), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('preferred_channel', sa.Enum('sms', 'email', 'push', 'call', name='notifychannel'), nullable=False),
    sa.Column('dnd_start', sa.Integer(), nullable=True),
    sa.Column('dnd_end', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['senior_id'], ['seniors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('family_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_family_members_senior_id'), ['senior_id'], unique=False)

    op.create_table('marketplace_services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_pln', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('marketplace_services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_marketplace_services_partner_id'), ['partner_id'], unique=False)

    op.create_table('vital_thresholds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('senior_id', sa.Integer(), nullable=False),
    sa.Column('vital_type', sa.Enum('heart_rate', 'spo2', 'systolic', 'diastolic', 'steps', 'sleep_hours', 'temperature', name='vitaltype'), nullable=False),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.Column('manual_override', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['senior_id'], ['seniors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vital_thresholds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vital_thresholds_senior_id'), ['senior_id'], unique=False)

    op.create_table('wearable_devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('senior_id', sa.Integer(), nullable=False),
    sa.Column('vendor', sa.Enum('xiaomi_zepp', 'apple_health', 'garmin', 'fitbit', 'generic', name='wearablevendor'), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['senior_id'], ['seniors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wearable_devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wearable_devices_senior_id'), ['senior_id'], unique=False)

    op.create_table('marketplace_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('senior_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('created', 'confirmed', 'cancelled', 'in_progress', 'completed', 'disputed', name='orderstatus'), nullable=False),
    sa.Column('amount_pln', sa.Float(), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('cancellable_until', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['senior_id'], ['seniors.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['marketplace_services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('marketplace_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_marketplace_orders_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketplace_orders_senior_id'), ['senior_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketplace_orders_service_id'), ['service_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketplace_orders_status'), ['status'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('senior_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Enum('green', 'yellow', 'red', 'purple', name='semaphorelevel'), nullable=False),
    sa.Column('channel', sa.Enum('sms', 'email', 'push', 'call', name='notifychannel'), nullable=False),
    sa.Column('mode', sa.Enum('digest', 'immediate', 'bypass_dnd', name='deliverymode'), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'failed', 'acknowledged', name='notificationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['family_members.id'], ),
    sa.ForeignKeyConstraint(['senior_id'], ['seniors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_recipient_id'), ['recipient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_senior_id'), ['senior_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_status'), ['status'], unique=False)

    op.create_table('vital_readings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('senior_id', sa.Integer(), nullable=False),
    sa.Column('vital_type', sa.Enum('heart_rate', 'spo2', 'systolic', 'diastolic', 'steps', 'sleep_hours', 'temperature', name='vitaltype'), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('measured_at', sa.DateTime(), nullable=False),
    sa.Column('breached', sa.Boolean(), nullable=False),
    sa.Column('audit_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['wearable_devices.id'], ),
    sa.ForeignKeyConstraint(['senior_id'], ['seniors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vital_readings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vital_readings_breached'), ['breached'], unique=False)
        batch_op.create_index(batch_op.f('ix_vital_readings_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vital_readings_measured_at'), ['measured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_vital_readings_senior_id'), ['senior_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vital_readings_vital_type'), ['vital_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vital_readings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vital_readings_vital_type'))
        batch_op.drop_index(batch_op.f('ix_vital_readings_senior_id'))
        batch_op.drop_index(batch_op.f('ix_vital_readings_measured_at'))
        batch_op.drop_index(batch_op.f('ix_vital_readings_device_id'))
        batch_op.drop_index(batch_op.f('ix_vital_readings_breached'))

    op.drop_table('vital_readings')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_status'))
        batch_op.drop_index(batch_op.f('ix_notifications_senior_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_recipient_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_level'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    op.drop_table('notifications')
    with op.batch_alter_table('marketplace_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marketplace_orders_status'))
        batch_op.drop_index(batch_op.f('ix_marketplace_orders_service_id'))
        batch_op.drop_index(batch_op.f('ix_marketplace_orders_senior_id'))
        batch_op.drop_index(batch_op.f('ix_marketplace_orders_created_at'))

    op.drop_table('marketplace_orders')
    with op.batch_alter_table('wearable_devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wearable_devices_senior_id'))

    op.drop_table('wearable_devices')
    with op.batch_alter_table('vital_thresholds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vital_thresholds_senior_id'))

    op.drop_table('vital_thresholds')
    with op.batch_alter_table('marketplace_services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marketplace_services_partner_id'))

    op.drop_table('marketplace_services')
    with op.batch_alter_table('family_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_family_members_senior_id'))

    op.drop_table('family_members')
    with op.batch_alter_table('data_processing_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_processing_logs_senior_id'))
        batch_op.drop_index(batch_op.f('ix_data_processing_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_data_processing_logs_action'))

    op.drop_table('data_processing_logs')
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partners_status'))
        batch_op.drop_index(batch_op.f('ix_partners_category'))

    op.drop_table('partners')
    # ### end Alembic commands ###
