"""disclosure logs

Revision ID: 0007
Revises: 0006
Create Date: 2026-07-14 11:36:44.098116
"""
from alembic import op
import sqlalchemy as sa


revision = '0007'
down_revision = '0006'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disclosure_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('senior_id', sa.Integer(), nullable=False),
    sa.Column('conversation_ref', sa.String(length=120), nullable=False),
    sa.Column('channel', sa.Enum('voice', 'sms', 'app', name='disclosurechannel'), nullable=False),
    sa.Column('disclosed', sa.Boolean(), nullable=False),
    sa.Column('disclosure_text', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['senior_id'], ['seniors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('disclosure_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disclosure_logs_conversation_ref'), ['conversation_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_disclosure_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_disclosure_logs_senior_id'), ['senior_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disclosure_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disclosure_logs_senior_id'))
        batch_op.drop_index(batch_op.f('ix_disclosure_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_disclosure_logs_conversation_ref'))

    op.drop_table('disclosure_logs')
    # ### end Alembic commands ###
