from __future__ import annotations

from typing import Any, Dict, Optional, Protocol


class STTBackend(Protocol):
    def initialize(self) -> bool: ...
    def shutdown(self) -> None: ...
    def is_loaded(self) -> bool: ...
    def status(self) -> Dict[str, Any]: ...


class TTSBackend(Protocol):
    sample_rate: int
    def initialize(self) -> bool: ...
    def shutdown(self) -> None: ...
    def is_loaded(self) -> bool: ...
    def status(self) -> Dict[str, Any]: ...

    async def synthesize(self, text: str) -> bytes: ...


class LLMBackend(Protocol):
    def initialize(self) -> bool: ...
    def shutdown(self) -> None: ...
    def is_loaded(self) -> bool: ...
    def status(self) -> Dict[str, Any]: ...

    async def generate(self, prompt: str) -> str: ...

